### ISSUE TITLE
Renderflow exception on iOS simulator

### ISSUE THREAD

**Issue by DK15** [lukepighetti/flutter-developers#10]
I was playing around this app to add my profile and observed renderflow exception on iOS simulator(iphone 8 - 11.4) under GroovinChip -> Pub Packages -> groovin_widgets, as below:
![screen shot 2019-01-08 at 2 26 20 pm](https://user-images.githubusercontent.com/16548367/50821196-9e911680-1354-11e9-8dac-bee40df3fec7.png)

I've a fix for it : to wrap `Text` widget inside `Flexible` widget which resolves issue, as below:

![screen shot 2019-01-08 at 2 31 00 pm](https://user-images.githubusercontent.com/16548367/50821285-d39d6900-1354-11e9-9833-08e7eab5971b.png)

I am unable to push my changes, as I am getting this error while creating pr:

remote: Permission to lukepighetti/flutter-developers.git denied to DK15.
fatal: unable to access 'https://github.com/lukepighetti/flutter-developers.git/': The requested URL returned error: 403

**Comment by lukepighetti** [comment]
@GroovinChip

**Comment by lukepighetti** [comment]
Not sure why you cannot make a PR. Did you try forking it to your account first before making a PR? Thanks for bringing up the issue. :)

**Comment by DK15** [comment]
yeah I tried that by forking earlier but for some reason it gave me same error, but I think I figured it out now. It had to do something with my login credentials.
Is it ok if I raise pr for the fix ?

**Comment by GroovinChip** [comment]
You can submit the fix, thanks for pointing it out

**Comment by DK15** [comment]
Thanks @GroovinChip and @lukepighetti , I raised the PR.

**Comment by lukepighetti** [comment]
PR accepted, thank you.
